### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by Code-Slave** [seatable/seatable#1]
Can get server to start. followed docs using  0.9.4 same error on .9.3 

sudo docker exec -it seatable /shared/seatable/scripts/seatable.sh start
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

i get the same error for all server, also for mysql 

Traceback (most recent call last):
  File "main.py", line 42, in <module>
    main()
  File "main.py", line 27, in main
    raise RuntimeError('Failed create tables, error: %s' % e)
RuntimeError: Failed create tables, error: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'db' ([Errno -5] No address associated with hostname)")
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by sniper-py** [comment]
Please show the logs of docker compose. And check the contents of docker-compose.yml to see if the correct path is configured for services: db: volumes:

**Comment by Code-Slave** [comment]
this is log from docker compose up

    volumes:
      - /pool/apps/seatable/mysql-data:/var/lib/mysql

Im running as sudo and not sudo for docker compose. Same error each time

i changed mysql-data to 777 and same issue

seatable-mysql | 2020-01-20 15:27:12+00:00 [Note] [Entrypoint]: Initializing database files
seatable-mysql | 2020-01-20 15:27:12 139816279099392 [Note] /usr/sbin/mysqld (mysqld 10.1.43-MariaDB-1~bionic) starting as process 89 ...
seatable-mysql | 2020-01-20 15:27:12 139816279099392 [Warning] Can't create test file /var/lib/mysql/2172574267bc.lower-test
seatable-mysql | 2020-01-20 15:27:12 139816279099392 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 2 "No such file or directory")
seatable-mysql | 2020-01-20 15:27:12 139816279099392 [ERROR] mysqld: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
seatable-mysql | 2020-01-20 15:27:12 139816279099392 [ERROR] Plugin 'Aria' init function returned error.
seatable-mysql | 2020-01-20 15:27:12 139816279099392 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.

**Comment by freeplant** [comment]
MySQL problem is not directly related to SeaTable. I suggest you to try to run in a new virtual machine.

**Comment by Code-Slave** [comment]
Well it is your docker setup that i am trying to run
