### ISSUE TITLE
Submitting form doesn't work for list type

### ISSUE THREAD

**Issue by asp100m** [seatable/seatable#10]
I created a table with columns of various types, and tried to insert data by a form.
After submitting, the data are inserted but left columns of list type blank.

The version is 0.9.5

**Comment by freeplant** [comment]
What list type do you mean? Do you have a screenshot?

**Comment by asp100m** [comment]
It's single select.
https://imgur.com/a/1Uyms19

**Comment by freeplant** [comment]
Thanks for reporting the issue. It will be fixed in the next release.

**Comment by freeplant** [comment]
Fixed in 0.9.6.
