### ISSUE TITLE
Export of looked up columns are not exported ?

### ISSUE THREAD

**Issue by mdartic** [seatable/seatable#100]
Hello,

It seems that if you export a view containing formula of "looked up columns", 
they are not exported (empty cells).

Do you think we could have the values inside ?

Other point, do you think it could be possible for reference columns to export something else than the row id ?
Maybe what we display on the column ?

Thanks

**Comment by freeplant** [comment]
The issue will be solved in version 1.1. 

Row name will also be exported rather than row id.

**Comment by mdartic** [comment]
Do you know when the release will be available ?

**Comment by freeplant** [comment]
The new version will be available in the next week.

**Comment by mdartic** [comment]
Thanks !
