### ISSUE TITLE
Select a collaborator even if dtable is not shared

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#102]
When we create a collaborator field, we need necessarily to share the table to him before we can reference it in the field. This is problematic if we don't want to share the table with him.

**To Reproduce**

- Go to any table
- Add a new Column
- Set Collaborateur as Type
- Add a new row
- Try to add a collaborator, at this stage you can see only collaborateur with whom you've shared the table

**Expected behavior**
The input should allow you to select any collaborator you should interact with (any collaborator that you're allowed to share data with).

**Comment by mont5piques** [comment]
1.1.0 Update : If a logged user submits a form related to the table, his name will be "xxxx@auth.local" if  the table is not shared with him.

**Comment by freeplant** [comment]
> 1.1.0 Update : If a logged user submits a form related to the table, the creator field will be "[xxxx@auth.local](mailto:xxxx@auth.local)" if the table is not shared with him.

This is already fixed.
