### ISSUE TITLE
GroupBy - Default to "Collapsed"

### ISSUE THREAD

**Issue by doodlemania2** [seatable/seatable#105]
When I create a view that has a Group By set up, I'd like the ability to default the view to collapse the nodes under each grouping instead of defaulting to expanded.

This:
![image](https://user-images.githubusercontent.com/5252217/86844439-aaef5000-c06d-11ea-8fb9-56b08592c56c.png)

Instead of:
![image](https://user-images.githubusercontent.com/5252217/86844602-ec7ffb00-c06d-11ea-949f-729b10809059.png)

**Comment by freeplant** [comment]
In version 1.3, there is a "collapse all" button in the groupby dialog.
