### ISSUE TITLE
Character Set?

### ISSUE THREAD

**Issue by doodlemania2** [seatable/seatable#106]
Is it possible the system (or the Python API) isn't using UTF-8 and instead using latin-1? Reason for asking, I can't make a field of type Long Text accept the ' (tick mark as in "we've") character:

UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 196: Body ('’') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by freeplant** [comment]
The literal strings in a Python file is UTF-8. Internally, Python use Unicode (UTF-16) when handling strings.
