### ISSUE TITLE
[BUG] Formula result is not returned by API if it contains a rollup instruction

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#109]
Usually formula fields are calculated and returned as a normal field in rows API request (thru python module).
But, for the specific case where we use a rollup instruction (or maybe refrencing a linked field also), the returned field is null.

**To Reproduce**

- Create a "customers" table with only Name fields
- Add 3 ou 4 customers
- Create a "orders" table with a customer field link to "customers" table
- Create an order row with a link to 2 customers for example
- Create a Formula field named "cutomer_count" that counts the customer number. Example: rollup('Customers', 'Name', 'count')
- Request the table rows thru the API, the  cutomer_count field is null

** Expected behavior**

The cutomer_count field in the API result should have the same value as the UI value.

**Comment by freeplant** [comment]
You can try again in the next release 1.1 in the next week.

**Comment by freeplant** [comment]
We have uploaded version 1.1.0 docker. Please give it a try.

**Comment by mont5piques** [comment]
Thanks, I'll try and I will update the issue.

**Comment by mont5piques** [comment]
It works perfectly, I'll close the issue.
