### ISSUE TITLE
Unable to drag first column

### ISSUE THREAD

**Issue by asp100m** [seatable/seatable#11]
The first column is immovable. You can't drag it directly or push it back by others.

The version is 0.9.5.
Browser is google chrome 80.0.3987.116.

**Comment by freeplant** [comment]
The first column is designed to be immovable. It is used as identifier of a row. It can't be deleted or moved.

We will add a help tip in the following release.

**Comment by asitemade4u** [comment]
Actually, even in Airtable one is not able to drag the first column.
