### ISSUE TITLE
[BUG] Can no longer add new images

### ISSUE THREAD

**Issue by cardinalfan1** [seatable/seatable#110]
I am using SeaTable 0.9.8.
I was able to add new images by copying and pasting into the image field. However, this is no longer working. And now when I try to export the table, I get an "internal server error". Any tips to debug?

**Comment by freeplant** [comment]
Please upgrade to the latest version and try again.

**Comment by cardinalfan1** [comment]
Upgrading didn’t work. Is there any way to force an export through command line? Since the web is not working

**Comment by freeplant** [comment]
What error do you have after upgrading?

**Comment by cardinalfan1** [comment]
Same issue --
It started out by not being able to add images to the image column. I also cannot export to DTABLE file

**Comment by freeplant** [comment]
Can you check the logs for error messages?
