### ISSUE TITLE
Version 1.1 of docker image doesnt work

### ISSUE THREAD

**Issue by Zmeu213** [seatable/seatable#111]
Please provide new example docker-compose configuration if there are any differences with version 0.9. Latest version doesnt work with old configuration, 404 in response on exported port

**Comment by sniper-py** [comment]
Please post details of the error.
Or you can deploy SeaTable according to the guidelines [Deploy SeaTable Community Edition with Docker](https://docs.seatable.io/published/seatable-manual/docker/ce-edition/Deploy%20SeaTable-ce%20with%20Docker.md).
