### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by NoverNobida** [seatable/seatable#113]
I followed the guide to deploy seatable(CentOS 7, apache), but failed: I can't open the website. I used `docker-compose up` and got this:
```
seatable     | runsv nginx: fatal: unable to start ./run: file does not exist
seatable     | 2020-08-23 09:56:12 Waiting Nginx 
seatable     | 2020-08-23 09:56:12 Waiting Nginx 
seatable     | 2020-08-23 09:56:12 Waiting Nginx 
seatable     | 2020-08-23 09:56:12 Waiting Nginx 
```

**Comment by freeplant** [comment]
![image](https://user-images.githubusercontent.com/109339/90999793-2b581900-e5fa-11ea-9425-f55c73f888ac.png)
