### ISSUE TITLE
Formula lookup columns cannot see computed columns in another table

### ISSUE THREAD

**Issue by shawngmc** [seatable/seatable#114]
I'm currently trying to make a three-table relationship (A - B - C), Each table should have multiple columns imported from another table. However, the 'edge' tables (A, C) cannot read computed fields (links to another table, formulas for pulling values from linked tables, etc.).

Reproduction
1. Create a new base
2. Create tables A, B and C, each with flat text columns (e.g. A1, A2, A3, B1, ...)
3. Populate a few rows with dummy data
4. Link tables A and B. B should now have an A1 column, and A should now have a B1 column.
5. Use a formula column to pull A2 into the B table (formula: {A1.A2})
6. Link tables B and C. B should now have an C1 column, and C should now have a B1 column.
7. Using a formula, try to add a computed column from table A to table C by way of the table B linkage. Both the linked field (formula: {B1.A1}) or the formula value (formula: {B1.A2}) will be invalid formulas,. They also do not show up in the linked columns list.

Expected behavior
- Formulas referencing computed fields in other tables should work
- The linked column list should include these computed columns

**Comment by freeplant** [comment]
Thanks for reporting the issue. We will try to solve the problem in version 1.4 in October.

**Comment by Mengnovich** [comment]
And this update in 1.4 will also enable the statistics plugin to compute linked data (between tables A and C as described above), I assume?
