### ISSUE TITLE
[Question] Docker image for seatable 1.3 ?

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#118]
On the website, a news post says that Seatable 1.3 is released (sep. 14) and I got a newsletter for this release but no docker image is available like other releases.

Are Docker releases stopped ?

Thanks.

**Comment by freeplant** [comment]
The docker version for 1.3 will be available in the next week.

The cloud version will be updated first. The docker version will be one or two weeks behind after fixing issues found in the cloud version. In this way, we don't need to release multiple docker versions.

**Comment by mont5piques** [comment]
Thanks a lot.
