### ISSUE TITLE
"Table" is very confusing

### ISSUE THREAD

**Issue by asitemade4u** [seatable/seatable#12]
I think the terms "Table"  and "Subtable" are very confusing in the interface.
Basically:

- Table is a group of at least one table = DATABASE
- subtable is any additional table added to the group = TABLE

It does not really make sense for whoever has worked with databases...
You could say instead:

- Schema/Group (the grouping of databases at the upper level)
- Database
- Table

**Comment by dada-dudu** [comment]
I agree, the terminology is anything but clear:  In the webinterface, the term "table" refers to a containter containing one or more "subtables". Once you are in one "table", the tabs are also called tables. Additionally, the API documentation introduces the term "dtable" (https://docs.seatable.io/published/seatable-api/home.md). Sporadically, you can also find the term in the web interface.

From the top of my head, this is the nomenclature used in other tools (container - table):
* Excel: workbook - worksheet
* Airtable: base - table
* Asana: project - list
* Zenkit: collection - table

Given the similarity to airtable, I think the the word-pair "base" - "table" would be good. But I can also the following combinations:
* "collection" - "table"
* "library" - "table"
* "repo" - "table"

From my point of view, the term "dtable" is super confusing. When I told people about SeaTable, they heard c-table.  Now introducing dtable, they are lost.

**Comment by freeplant** [comment]
We will change the term to **base**. For APIs, the old term dtable will be used as only advanced users will use APIs.
