### ISSUE TITLE
[Feature] Add a rollup with filter formula function

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#120]
In a formula field, we can use ```rollup("link-column-name", "column-name-in-linked-record", summary)``` to aggregate linked fields. 

It would be nice if we could have a function to filter the aggregated records ```rollup_with_filter("link-column-name", "column-name-in-linked-record", summary, filter)``` .

Example : A customer table has a linked column named Orders :

 ```rollup_with_filter("orders", "price", "sum", "canceled != 1")```

**Comment by freeplant** [comment]
It is implemented in the latest version.

**Comment by martinkoutecky** [comment]
@freeplant there are no examples for how this can be used and I'm struggling with it. I have a linked column and I would like to count the number of occurences of one particular element, so I thought I could do rollup with "count" and the filter condition being that the string equals something, but I don't know how to do this.

(Equivalently for me, there is no function to count the number of occurrences of a substring in a string; I think having this would also be really useful.)

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seatable.io . Some screenshots will help a lot.
