### ISSUE TITLE
Disable the built-in NGINX instance

### ISSUE THREAD

**Issue by ArjonBu** [seatable/seatable#122]
Is there a way to completely disable NGINX? I am using an external nginx instance and I want to disable the currently builtin nginx instance. I am having trouble making it work. 

From a best practices point of view, it's always better to not include the reverse proxy inside the application because usually this is handled by something external. 

Thank you

**Comment by freeplant** [comment]
Nginx is part of SeaTable to hide the detailed internal multiple components. It makes sure SeaTable looks like a simple application to the outside. We don't have a plan to Nginx. But you are free to add an extra Nginx proxy.

**Comment by gouravkr** [comment]
> But you are free to add an extra Nginx proxy.

The problem with this is that there are no instructions anywhere on how to make this work and it's very difficult to make it work with https. It's relatively simple to configure without https, but the moment I configure https on the outer nginx, Seatable stops working with no indication as to how to resolve this.
