### ISSUE TITLE
CORS Issues

### ISSUE THREAD

**Issue by andrewfam** [seatable/seatable#127]
Having cors issues with the project.
Possible to install https://pypi.org/project/django-cors-headers/ as part of the default?

**Comment by martinkoutecky** [comment]
I'm probably having the same problem. @andrewfam what do django-cors-headers have to do with it? Can I somehow fix the bug using it?

**Comment by andrewfam** [comment]
I ssh directly into the beatable docker instance, install django-cors-headers and make the relevant changes to the settings files.
Not ideal as every time the docker resets I need to remember to do it.

**Comment by martinkoutecky** [comment]
Sorry I deleted my post - I discovered that really my problem was wrongly set URLs in the config files. So actually I'm not running into CORS issues, which makes me wonder what causes your problems. Thanks for your response though!

**Comment by freeplant** [comment]
It is likely a deploy problem. I will close the issue.
