### ISSUE TITLE
Bug: seatable requesting data via http on https setup

### ISSUE THREAD

**Issue by despens** [seatable/seatable#131]
I am using seatable developer edition 1.8.0. I removed the nginx container from the docker-compose file because I am using my own nginx proxy to provide https.

It is possible to create tables and change system and user settings, but trying to access a created table only produces a blank window with a spinner at the center.

Looking at the browser console, I noticed seatable requests a single javascript resource via http instead of https, which is consequently blocked by the browser:

```
Blocked loading mixed active content “http://tables.machine.cool/dtable-server/dtables/f53a5713-57cd-4bc0-ac3a-4df6af28bb3f?lang=en” commons.chunk.5c8c2f624858.js:1:2383094
```

After this failed requests, the console is just overflowing with JavaScript errors.

All other resources are loaded via https.

**Comment by agrimpelhuber** [comment]
Had the same problem in a similar setting.

Find `dtables_web_settings.py` in your `conf` directory. Change all http:// links to https://. Restart seatable.

Worked for me.
