### ISSUE TITLE
How to change db port?

### ISSUE THREAD

**Issue by freechw** [seatable/seatable#133]
My server have another mariadb container,  it use 3306 port,   how to change seatable  db  port in docker-compose.yml?

**Comment by ktomk** [comment]
Port 3306 should be fine, that is the expected one. Into which issue are you running?

**Comment by freechw** [comment]
My server has used 3306 port,  so  I must change  the port when run seatable,  I changed the port in docker-compose.yml files,  it looks like:
`services:
  db:
    image: mariadb:10.5
    container_name: seatable-mysql
    ports:
      - "13306:3306"
`
but it is report error when run the seatable.

**Comment by ktomk** [comment]
Hmm, weird. The default `docker-compose.yml` has no published ports at all for the `db` service, so there should have been no conflict as docker-compose creates one network per project. You might get more feedback if you join the seatable forums and post in https://forum.seatable.io/c/bugs-issues/5 - Issues here are not fitting well for setup instructions. Please create a post there and also add the error messages you get so it is easier to give feedback.
