### ISSUE TITLE
Grouped view makes it possible to circumvent column editing restriction [security]

### ISSUE THREAD

**Issue by agrimpelhuber** [seatable/seatable#136]
Protecting a column against changes (by certain users, or in general) seems to work just fine.

_Unless_ you (or someone else) group the view by this very column which you have protected. After that, everyone can change the column's value by dragging and dropping rows from one group to another.

This should be prevented.

**Comment by freeplant** [comment]
Thanks for reporting the issue.

**Comment by freeplant** [comment]
It should have been fixed in the latest version.
