### ISSUE TITLE
Wrong link target of "blank" instead of "_blank"

### ISSUE THREAD

**Issue by windware-ono** [seatable/seatable#139]
When links are clicked in a long text modal, a tiny popup shows up where you can click to open the link but the link has a wrong target which is set as "blank" instead of the supposedly correct "_blank", which in turn opens any links clicked in the same tab that overrides the previously opened links having same named target.

The link in question has a class name of "seafile-ed-hovermenu-link".
This is present in version 2.1.0.

**Comment by freeplant** [comment]
Thanks for reporting the issue. It will be fixed soon.

**Comment by freeplant** [comment]
Fix will be included in version 2.4.
