### ISSUE TITLE
Link to other records does not work

### ISSUE THREAD

**Issue by asitemade4u** [seatable/seatable#14]
Is the function already implemented?
It does not work in version 0.9.5
Contrary to the limitations in Airtable, Seatable should be able to link records between tables belonging to different groups.

**Comment by freeplant** [comment]
You can only link to sub-table in the same table currently. But you can publish a view of a sub-table as **common dataset**.  Then you can import a common dataset to a sub-table, and link records in it.

In a later version, we will add a feature that sync the imported sub-table with original view.

**Comment by weismannweb** [comment]
I am having this issue too.  You can see it here in this video:  https://drive.google.com/file/d/1AhftR5p4U-OGWViRizcmFE-yGoKAv4N_/view

Unless I am using it wrong I don't see the drop-down showing the other table I want to link to.  I even entered dummy records thinking it would only work with at least one record that exists.  No, go. It says it only works with sub tables so I assume those are the tabs (tables within master table).

Also, your documentation on this is slim:  https://docs.seatable.io/published/seatable-user-manual/link.md

Can you write up the documentation or confirm if we have a bug?  I am a huge fan of this software.  I would gladly pay for the self-hosted pro version.  One more question.  Can it handle 500,000 or so records in one sub table?

Thanks!

**Comment by freeplant** [comment]
@weismannweb Thanks for the video. It is really a bug. If you create a new column with type "Link other records", it can work. But if you convert existing column to "Link other records", it does not work.

We will fix the bug in the next release 0.9.7. For now, you can just create a new column to workaround this issue.

For the second question, I'm afraid we have only tested with 10,000 records yet. As we load all data in the browser, I'm afraid 500,000  records will take too much memory, it can't work yet.

In the future, I think one solution is to mark some records as _cold_ , so they do not need to be loaded and only fetched on demand.

Can you share more about your use case for 500,000 records?

**Comment by weismannweb** [comment]
Hi,

My use case....

Crawl amazon and collect data in two ebook categories and collect data on them.  Do the same for 6 other books platforms.
Create sub tables in seatable for Table Books  90,000 books, Table Authors 50,000 authors, Table Readers 400,000 readers, Table Reviews 500,000book reviews (only collecting reviewer url, name and stars)  Then have relationships between all those tables.

Also, another need of mine is multiple Links to other records in the same sub table.
