### ISSUE TITLE
error amount form to table

### ISSUE THREAD

**Issue by yblis** [seatable/seatable#145]
Hello

First of all, sorry for my English...

I found during my tests made on seatable, that the form does not return the right amounts:

for example:
when writing: 12,00
![image](https://user-images.githubusercontent.com/10268910/159175233-573cc151-1111-4b80-9466-0028127f1c96.png)

it adds in the table: 1500,00
![image](https://user-images.githubusercontent.com/10268910/159175277-c84db588-a74b-4494-b005-b4d45ce075fc.png)

Other example :
When writing: 12,50
it adds in the table: 1250,00

I use the last version of seatable.

thanks for help

**Comment by Michael18811380328** [comment]
Hey yblis, 

Thank you for your attention to seatable!

In the latest version of seatable, I tested the number column (Euro format) submitted in the form, according to the steps you said(When writing: 12,50 in form, it adds in the table: 1250,00). The number in the form is normal after submission. You can test it with the latest version.

Here are my column formatting and form submission.
<img width="349" alt="截屏2022-11-14 18 15 23" src="https://user-images.githubusercontent.com/37589122/201635726-8065583e-3301-441d-9475-8cd0b2b0ac2d.png">
<img width="509" alt="截屏2022-11-14 18 15 07" src="https://user-images.githubusercontent.com/37589122/201635742-267a000c-9044-4db2-8066-1b12a591c997.png">
<img width="906" alt="截屏2022-11-14 18 14 40" src="https://user-images.githubusercontent.com/37589122/201635767-ad5d7ea6-317e-4f05-a7dd-a17a0b35ee9e.png">

**Comment by yblis** [comment]
Hello

I confirm that this issue is resolved with the latest seatable update.

Thank you for your work!

👍
