### ISSUE TITLE
Add CSV import or give map of the data

### ISSUE THREAD

**Issue by asitemade4u** [seatable/seatable#15]
I tried to understand the structure of the MariaDB database but could not figure out where the records were.
Unfortunately, I was unable to import data into the database directly, using the import functions of DBeaver.
Is there a way to import a CSV file into the database, either from the Seatable interface, a plugin, or from the database itself?

**Comment by freeplant** [comment]
We will add the feature of import CSV file later.

The second way:

You can check https://github.com/seatable/seatable-scripts-examples/tree/master/python/sync_from_mysql

Modify the Python script to meet your need.
