### ISSUE TITLE
Blurry logo on Web site seatable.io

### ISSUE THREAD

**Issue by paulmenzel** [seatable/seatable#159]
The [logo](https://seatable.io/wp-content/uploads/2021/09/seatable-logo.png) on the [Web site](https://seatable.io/) is blurry on HiDPI displays.

    $ file seatable-logo.png
    seatable-logo.png: PNG image data, 140 x 36, 8-bit colormap, non-interlaced
    $ identify seatable-logo.png
    seatable-logo.png PNG 140x36 140x36+0+0 8-bit sRGB 1395B 0.000u 0:00.000

![seatable-logo](https://github.com/seatable/seatable/assets/9318792/83f97483-fc97-4a35-872b-29db0848e07b)

**Comment by christophdb** [comment]
I replaced the logo on seatable.io with an svg-file. Now it should scale much better.

**Comment by paulmenzel** [comment]
Nice. Even directly embedded in the HTML source.

PS: Firefox can’t save it then, but no problem. I copied it from the source, and [it](https://github.com/seatable/seatable/assets/9318792/fe133f6e-3863-41e5-af65-a961c8dd368a)’s size is 5.4 kB.
