### ISSUE TITLE
Link to other records [not only first column]

### ISSUE THREAD

**Issue by voljen** [seatable/seatable#16]
Hi,
thanks for this project. Is there a way to create a link to other records specifying which column to use?
If I have a Table A structure as the following:

**Function | Owner**
HR | Alfa
Legal | Beta

How can I create in Table B a column that when I chose the related record with HR will automatically insert the Owner value as follow:

**Activity | Function | Owner**
Hire new employees | HR | Alfa

Where HR is a related record, while Alfa should be automatically imported

Thanks in advance

**Comment by freeplant** [comment]
The feature you want is called "Lookup column" in other products. We will add such a feature in version 0.9.8.

**Comment by voljen** [comment]
Thanks for the quick reply

**Comment by freeplant** [comment]
The feature will be added in version 1.0
