### ISSUE TITLE
API image upload - thumbnail missing

### ISSUE THREAD

**Issue by realbuz** [seatable/seatable#161]
I am uploading an image into an image column via the API without issues. However the icon for the image in the database view is generic and not showing a tiny preview like when I upload it directly.

![b786c770d9716088d303d6c30d3e50de12d221a2](https://github.com/seatable/seatable/assets/292446/3bbc1e25-b53f-456a-be50-bfbe387f72a7)

**Comment by freeplant** [comment]
Replied in the forum.

**Comment by realbuz** [comment]
As replied on the forum, I think the issue is how seatable deals with images URL that are not straight jpg or png or other.  Example : 

http://books.google.com/books/content?id=FVO7CgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api
