### ISSUE TITLE
Share table between bases

### ISSUE THREAD

**Issue by D1reW0lf** [seatable/seatable#167]
Hi all. 

Is it possible to share a table (or a column of a table) between different bases?
I tried to search here but without any luck. 

Thank you.

**Comment by freeplant** [comment]
Have you looked into the common database feature?

**Comment by D1reW0lf** [comment]
@freeplant Thank you. 
I'll take a look

**Comment by D1reW0lf** [comment]
> Have you looked into the common database feature?

That did the trick.
Thank you so much.
