### ISSUE TITLE
OAuth feature ?

### ISSUE THREAD

**Issue by mdartic** [seatable/seatable#19]
Hello,

And thanks a lot for your hard work to make this project alive.

One question, can we already wire the authentication of seatable to a OAuth provider ?
I don't know how it's related, and how it's using code from seafile, but as seafile support this [since 6.2.3](https://download.seafile.com/published/seafile-manual/deploy/oauth.md), maybe it's included in seatable ?

And if not, do you plan to integrate it ?

**Comment by freeplant** [comment]
I'm sorry we have a different strategy for SeaTable. The OAuth and SAML feature will only be available in pro edition for SeaTable.

**Comment by mdartic** [comment]
Ok, thanks for your quick reply.
I'm searching the codebase, but it's not already published, am I wrong ?
I can inspect maybe the docker container.
Is there a way to import users in seatable ? 
Via LDAP, or do we have to inject them in the database directly ?

**Comment by freeplant** [comment]
You can use the API to add users: https://docs.seatable.io/published/seatable-api/dtable-web-v2.1-admin/users.md
