### ISSUE TITLE
Can't start seatable from docker 

### ISSUE THREAD

**Issue by jorgy80236** [seatable/seatable#2]
I am using the docker-compose.yml file, and when I do I get the error from my browser:
```
502 Bad Gateway
nginx/1.14.0 (Ubuntu)
```

From my console window, the only thing that seems relevant is:
```
seatable     | nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)
seatable     | This is a idle script (infinite loop) to keep container running.
```

I edited the docker-compose.yml file and got the same error in my browser from both 0.9.3 and 0.9.4.

**Comment by freeplant** [comment]
We will check the problem after coming back from holiday.

**Comment by jorgy80236** [comment]
Sounds good.  Thank you.

**Comment by sniper-py** [comment]
Please execute `docker-compose down`, then restart seatable and try again

**Comment by jorgy80236** [comment]
I did a `docker-compose down` and then a `docker-compose up`, but am still getting the same error in my browser.  Thank you.

**Comment by luketainton** [comment]
I am also seeing this problem.

**Comment by freeplant** [comment]
Can you try to enter into the docker and manually start the Nginx process?

**Comment by freeplant** [comment]
One more question, did you use HTTPS or HTTP?

**Comment by luketainton** [comment]
@freeplant NGINX must be running for it to return a 502 error.

**Comment by sniper-py** [comment]
Please execute `docker exec -it seatable nginx -s reload` before `docker exec -d seatable /shared/seatable/scripts/seatable.sh start`.

If the error is still reported, please check if the file `shared/seatable/conf/nginx.conf` exists.

**Comment by freeplant** [comment]
Can you try enter into the docker and run  `nginx -s reload`? We think it is a bug caused by the enterpoint.sh called `nginx -s reload` before Nginx process started. So run the command manually may fix the problem.

**Comment by jorgy80236** [comment]
Okay, running  `docker exec -d seatable /shared/seatable/scripts/seatable.sh start` enables me to get a login page.   Will try to login and then update here with results.

**Comment by RasHas** [comment]
I have the same issue. `docker exec -d seatable /shared/seatable/scripts/seatable.sh start` gets rid of `502 Bad Gateway`, but now I just get `Page Unavailable` with a subtext:

> Sorry, but the requested page is unavailable due to a server hiccup.
> Our engineers have been notified, so check back later.

**Comment by freeplant** [comment]
@RasHas Can you check dtable_web.log for error messages?

**Comment by KyleTryon** [comment]
> Please execute `docker exec -d seatable /shared/seatable/scripts/seatable.sh start`.
> 
> `502 Bad Gateway` means nginx is ready but seatable server is not running.
> Please show `/opt/seatable/logs/dtable_web.log` and `gunicorn-error.log`

I was experiencing the same issue, I now too get a login screen after running this.

**Comment by freeplant** [comment]
The problem is likely caused by start the program before the database initialization finishing. We have updated our document: 

![image](https://user-images.githubusercontent.com/109339/80201518-d78ef080-8656-11ea-909f-dca427d6c7d0.png)

**Comment by endolith** [comment]
I've let it run until the `idle script` message:

```
... 
seatable-mysql | 2023-09-08  4:14:31 0 [Note] Server socket created on IP: '::'.
seatable-mysql | 2023-09-08  4:14:31 0 [Note] Reading of all Master_info entries succeeded
seatable-mysql | 2023-09-08  4:14:31 0 [Note] Added new Master_info '' to hash table
seatable-mysql | 2023-09-08  4:14:31 0 [Note] mysqld: ready for connections.
seatable-mysql | Version: '10.5.22-MariaDB-1:10.5.22+maria~ubu2004'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
seatable     | 2023-09-08 00:14:33 This is an idle script (infinite loop) to keep container running. 
```

and then stopped it and run the next command in [the instructions](https://admin.seatable.io/docker/Developer-Edition/Deploy%20SeaTable-DE%20with%20Docker/) ("Run docker-compose again, this time in detached mode:"):

```
> docker-compose up -d
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Starting seatable-memcached ... done
Starting seatable-mysql     ... done
Starting seatable-redis     ... done
Starting seatable           ... done
```
and when I access `http://localhost:8234/` it says:

> 502 Bad Gateway
> nginx/1.22.1

if i then run `docker exec -d seatable /shared/seatable/scripts/seatable.sh start`, it changes to 

> Page unavailable
> 
> Sorry, but the requested page is unavailable due to a server hiccup.
> 
> Our engineers have been notified, so check back later.
