### ISSUE TITLE
Possible to reference total sums of other subtables?

### ISSUE THREAD

**Issue by ffranke** [seatable/seatable#20]
Hey there!

I want to reference values in another subtable. Example: I have all costs per month in subtable A. All other business expenses in subtable B. I want to calculate with the sums of each subtables in subtable C. 

Is that possible yet? How do I reference different subtables in Formula and how to reference total sums of subtables in Formula?

Thanks!
Florian

**Comment by freeplant** [comment]
The formula is for calculating a value from the same row. This is different from Excel.

Your request can be achieved by writing a plugin or a background script using Javascript or Python.

**Comment by ffranke** [comment]
Hey Daniel!
Thanks for the quick reply. Ok, I think I need to reasses what to do with seatable then. In my current understanding it's more database than spreadsheet at the moment.
Keep up the good work, thanks!
Florian
