### ISSUE TITLE
Where could we access the source code ?

### ISSUE THREAD

**Issue by mdartic** [seatable/seatable#21]
I was searching the repo to read the sourcecode and understand how all this work.
We are configuring docker to make it work with haproxy, and are experiencing some issues.
Before asking questions, we want go deeper in the code and understand by ourselves and avoid some easy-to-answer questions.
Is the code available somewhere ?

**Comment by freeplant** [comment]
You can check the readme:

SeaTable consists of following component

* dtable-web: The web site for manage tables.
* dtable-server: Store the tables and provide collaborating feature.
* dtable-events: Background maintenance tasks
* seaf-server: Store attachments (files and images), see  https://github.com/haiwen/seafile-server
* ccnet-server: Will be removed later.

The source code is in the docker image, under folder `/opt/seatable/` .

We are still working on private repositories to not break our current workflow. When 1.0 come out, we will move the code to public repositories and spend some time to change our workflow.

**Comment by mdartic** [comment]
Thanks you again for your quick reply.
I understand, and we'll check the code in the docker.
For dtable-server, if it is under a proprietary license, does it mean we won't be able to make pull request and/or access the code on a public repo ?

**Comment by freeplant** [comment]
> For dtable-server, if it is under a proprietary license, does it mean we won't be able to make pull request and/or access the code on a public repo ?

We don't have a plan to put dtable-server under a public repo.

**Comment by mdartic** [comment]
Ok, 
One last question, could we use Seatable in "enterprise" projects ?
Or is the "proprietary license" could limit us (or terms of services ?) ?
I didn't read anything like this in https://docs.seatable.io/published/cloud-service/SeaTable-Terms-of-Service.md, but I'm asking in case of.

**Comment by freeplant** [comment]
The term is only for cloud service. The cloud service is still a demo purpose only now.

You can find the license term for the self-hosted community edition at https://docs.seatable.io/published/seatable-manual/home.md

SeaTabe community edition should not be used to provide SaaS service or as a part of your SaaS service. Other kinds of usage are okay, including

* Use it internally in your company.
* Personal or home use.
* Use it to collaborate with your customers

Use it for projects for your customers is also okay. As long as you use a separate server for each of your customers.

**Comment by mdartic** [comment]
Ok, thank you for being so specific.

**Comment by lonesomewalker** [comment]
Seems this is still not resolved, because still no source code published.

And remember, your product is based on GPL...
Will have an eye on this now.

**Comment by freeplant** [comment]
> And remember, your product is based on GPL...

Which part do you mean?

SeaTable as a whole is not based on GPL. Some parts are released under open source license.

**Comment by lonesomewalker** [comment]
> > And remember, your product is based on GPL...
> 
> Which part do you mean?
> 
> SeaTable as a whole is not based on GPL. Some parts are released under open source license.

And SeaTable is NOT running without these dependencies -> GPL is very easy to understand in this case...
