### ISSUE TITLE
Convert text date to real date

### ISSUE THREAD

**Issue by hallisey** [seatable/seatable#22]
Hi team, great product. Is there anyway to convert a text column with dates to a date column with dates? Everytime I do this they disappear. It would also be good to copy and paste dates from an Excel or CSV into the system.

**Comment by freeplant** [comment]
What date format do you use? We support several formats that can be converted from text to date, like '2020-01-02', '2020.01.02'.

**Comment by hallisey** [comment]
Thank you very much for the quick response.  The date format I was using was DD/MM/YYYY, I will try to convert to that date format first. In general, what is the recommended method for importing data (apart from copying and pasting?) if you have lots of tables and lots of columns (with column names on the first row) in each table (e.g. a well-used Airtable base). There doesn't seem to be a CSV import.

**Comment by freeplant** [comment]
We support CSV import when you create a new table inside a base in version 0.9.7. Currently all columns will be text column when imported, which can be improved in a future release.

**Comment by hallisey** [comment]
Thank you, this is great!
