### ISSUE TITLE
How to import data?

### ISSUE THREAD

**Issue by hallisey** [seatable/seatable#23]
I would like to import data from another product. I have access to CSV and APIs. What is the best way to import data without losing data? Every time I try to configure columns (i.e. convert to text to Link to another record, or text to date) I lose data.

**Comment by freeplant** [comment]
As replied in another thread, converting date depends on your format. Link is not supported to convert directly. You can check our Python API if you can use API. We have also an example that sync MySQL database to SeaTable.
