### ISSUE TITLE
performance of grouping

### ISSUE THREAD

**Issue by miconx** [seatable/seatable#24]
we have imported a csv file with about 9000 rows and 15 columns (only text & numbers)
then we made a grouping by only 1 column (+sorting) 
now if we wanna use this table every click produces 100% browser cpu usage and the table is completely unresponsive - i would asume an issue with a client side javascript library? 
what can we do in order to improve the performance  ? 
i can provide the dtable export file if necessary for testing?

**Comment by freeplant** [comment]
It is a known issue for grouping. Currently a whole group is rendered instead of only visible rows in a group. If you have a large group, the performance is poor.

Can you send your file to us? We will improve the performance in the next release and check with this file.

**Comment by miconx** [comment]
[MEDALP-TABLES_Tarife_aktuell_2018-comma.csv.zip](https://github.com/seatable/seatable/files/4473503/MEDALP-TABLES_Tarife_aktuell_2018-comma.csv.zip)
[MEDALP-TABLES_Tarife_aktuell_2018-comma.xlsx](https://github.com/seatable/seatable/files/4473505/MEDALP-TABLES_Tarife_aktuell_2018-comma.xlsx)

great!
thats the file - if you group it after column "Versicherung" you can reproduce the lag
thanks

**Comment by freeplant** [comment]
Fixed in v0.9.8.
