### ISSUE TITLE
BUG: Localization issue with calendar widget

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#30]
There is some chinese whene using a datetime calendar

**Comment by freeplant** [comment]
Can you upload a screenshot?

**Comment by mont5piques** [comment]
![image](https://user-images.githubusercontent.com/4046624/79467325-f4477a80-7ffd-11ea-9b9f-d0a0e29cd9a6.png)

It happens with dates accurate to minute and clicking on a specific hours on the right

**Comment by freeplant** [comment]
Fixed in v0.9.8.
