### ISSUE TITLE
The function of cell's lower right corner

### ISSUE THREAD

**Issue by asp100m** [seatable/seatable#37]
I noticed that there is a tiny square at lower right of selected cell.
And I tried to drag it to cover other cells, it doesn't work as I expected.
Actually, It did nothing. If it can duplicate or replace cells, that will be great.

**Comment by freeplant** [comment]
The feature will be added in the next version 0.9.8. It can *smartly* duplicate cells as in Excel.

**Comment by freeplant** [comment]
Fixed in v0.9.8.
