### ISSUE TITLE
Unable to import base from dtable file

### ISSUE THREAD

**Issue by asp100m** [seatable/seatable#41]
I tried to import a dtable file, but the ui stuck at progress dialog.
And the browser console shows messages in [import_error_msg.txt](https://github.com/seatable/seatable/files/4537941/import_error_msg.txt) repeatedly.

Therefore, I reloaded the page. I saw the imported base is in My Tables and opened it. It gave me an empty page with browser console messages in [open_imported.txt](https://github.com/seatable/seatable/files/4537983/open_imported.txt).

**Comment by freeplant** [comment]
Can you check whether there are related error message in dtable_web.log and dtable-server.log?

**Comment by asp100m** [comment]
There is no related error message in dtable_web.log and dtable-server.log.
I moved those 2 files and restart service by seatable.sh restart, then I import a dtable file again.
The operation is stuck and the new log files haven't any newer message.

Additionally, I recently updated seatable from 0.9.5 to 0.9.7.
But there is no sql script for 0.9.6->0.9.7, so I only applied 0.9.5->0.9.6.
Would this cause any problem?

**Comment by freeplant** [comment]
The upgrade to 0.9.7 is not related to the problem.

Can you send the dtable file to us?

**Comment by asp100m** [comment]
Here is the dtable file.
https://www.dropbox.com/s/v13b4dib1pwhnex/tmp6.dtable?dl=0

**Comment by freeplant** [comment]
This file works fine in my server. We will add more debug information in the next release.

**Comment by asp100m** [comment]
Here is har file from chrome if needed.
https://www.dropbox.com/s/kyszrohv58z2ajt/import_base.har?dl=0

**Comment by asp100m** [comment]
Here is [dtable_web.log](https://github.com/seatable/seatable/files/4632598/dtable_web.log) on 0.9.8 and nothing is interesting in dtable-server.log.
The import function works at first upload, then it's always failed.

**Comment by freeplant** [comment]
It is caused by dtable-events process dead. Can you send post dtable-events.log?

**Comment by asp100m** [comment]
Here is [dtable-events.log](https://github.com/seatable/seatable/files/4632967/dtable-events.log).

**Comment by asp100m** [comment]
Here is [dtable_web.log](https://github.com/seatable/seatable/files/4823746/dtable_web_1_0_0.log) on 1.0.0.

**Comment by freeplant** [comment]
We have find a possible cause for the problem. A fix will be included in version 1.1.

**Comment by asp100m** [comment]
I tried it on 1.2.0 and it works. 👍
