### ISSUE TITLE
Troubles with copy & paste multiple checkbox

### ISSUE THREAD

**Issue by asp100m** [seatable/seatable#42]
The first problem:
The first copied will not be pasted to the target cell.
For example, a checkbox column has 6 cells and cells(1, 2, 3) are checked.
If I select cells(1, 2, 3) and copy-paste them to the cell 4, the cells(5 & 6) will be filled correctly. But the cell 4 is not, it's unchecked.

The second problem:
At the moment, the cursor of table is on cell 4. I accidentally pressed 'v', and the cell 4 becomes checked. If I deselect the cell 4 (by select others), the cell 4 shows empty. But when I select cell again, it shows it's checked.

seatable version 0.9.7
google chrome 80.0.3987.163

**Comment by freeplant** [comment]
The problem is solved in 0.9.8.
