### ISSUE TITLE
Copying from cells in public table view

### ISSUE THREAD

**Issue by sswatson** [seatable/seatable#44]
If you share a table with an external link, then people viewing the table with that link can copy a _range_ of values, but it doesn't seem to work to highlight a value from a single cell. 

This comes up, for example, if the value in the cell is a link, and the viewer wants to copy that link and paste it into their browser's URL bar. This is particularly important since there isn't a URL column type.

**Comment by freeplant** [comment]
We will check the problem.

**Comment by Michael18811380328** [comment]
> If you share a table with an external link, then people viewing the table with that link can copy a _range_ of values, but it doesn't seem to work to highlight a value from a single cell.
> 
> This comes up, for example, if the value in the cell is a link, and the viewer wants to copy that link and paste it into their browser's URL bar. This is particularly important since there isn't a URL column type.

Hey sswatson,
In the external link page, cell is read-only, so we can't choose and highlight a value from a single cell. But we can copy a cell which contains a link (via ctrl + C) and paste it into URL bar just like below. We can't reproduce your problem.

<img width="244" alt="屏幕快照 2020-05-08 14 40 29" src="https://user-images.githubusercontent.com/37589122/81378892-b213e380-913a-11ea-8b01-2a5e3701921e.png">

Could you please take a picture and describe it in detail?

**Comment by sswatson** [comment]
On the date that I posted the issue, a person I had sent an external link to described the behavior, and I was able to reproduce it at that time. However, it works perfectly now, on the same browsers I tested it on originally. Thanks!
