### ISSUE TITLE
Multi-Select does not work

### ISSUE THREAD

**Issue by cardinalfan1** [seatable/seatable#45]
Hello
Using latest version of seatables on docker
Browser: tried safari, chrome on macos. Chrome on windows

I am able to add options to a multi select field but when entering data cannot choose an actual option.

Would appreciate help on trouble shooting.
Thx

**Comment by cardinalfan1** [comment]
Upon further testing, it seems to not work with the selection options are long strings. Short strings seem to work ok

**Comment by cardinalfan1** [comment]
Actually, I figured out that I can add a long string to the list of options and select it.
However, when you try to search for a part of the name of the option, it breaks the whole system permanently.

**Comment by cardinalfan1** [comment]
react-dom.production.min.js:169 Uncaught TypeError: r.push is not a function
    at t.n.onSelectOption (MultipleSelectEditor.js:71)
    at Object.m (react-dom.production.min.js:81)
    at T (react-dom.production.min.js:101)
    at react-dom.production.min.js:105
    at _ (react-dom.production.min.js:125)
    at D (react-dom.production.min.js:153)
    at k (react-dom.production.min.js:143)
    at P (react-dom.production.min.js:167)
    at yn (react-dom.production.min.js:1622)
    at ue (react-dom.production.min.js:7171)

This is the error I get

**Comment by freeplant** [comment]
We will check the problem.

**Comment by Michael18811380328** [comment]
> Upon further testing, it seems to not work with the selection options are long strings. Short strings seem to work ok

<img width="587" alt="2" src="https://user-images.githubusercontent.com/37589122/81468579-09858280-9213-11ea-8e25-f2fb34aff0d4.png">

Thank you for using seatable. We test multiple with long string options. It seems to work well. Could you please take a picture or give us an example of a wrong long string?

**Comment by Michael18811380328** [comment]
> Actually, I figured out that I can add a long string to the list of options and select it.
> However, when you try to search for a part of the name of the option, it breaks the whole system permanently.

<img width="596" alt="1" src="https://user-images.githubusercontent.com/37589122/81468707-c5df4880-9213-11ea-9f6d-87972b46ab36.png">

We test multiple selection with long string options.
And we try to search the "Methyl dihydrogen phosphatel
". It also seems to work well.  Could you please take another picture?

**Comment by cardinalfan1** [comment]
Hello
Thank you for checking on this
Chrome 81.0.4044.129 (Windows). Also tried chrome and safari on MacOS
Latest SeaTable (0.9.7)
-----------------------------------------

Here are steps to reproduce:

1. Create multi-select field
2. Add these items as a test (without the quotation marks):

 - "11010 - Debridement   including removal of foreign material associated with open fractures and or   dislocations; skin and subcutaneous tissues"
 - "11011 - Debridement   including removal of foreign material associated with open fractures and or   dislocations; skin, subcutaneous tissue, muscle fascia, and muscle"
 - "11012 - Debridement   including removal of foreign material associated with open fractures and or   dislocations; skin, subcutaneous tissue, muscle fascia, muscle, and bone"

3. At this point everything should be working. You should be able to select any of these items.

4. Try to search for "11011" and then click on the item
5. Clicking on the item will perform no action and will produce the javascript error I showed earlier:

react-dom.production.min.js:169 Uncaught TypeError: r.push is not a function
at t.n.onSelectOption (MultipleSelectEditor.js:71)
at Object.m (react-dom.production.min.js:81)
at T (react-dom.production.min.js:101)
at react-dom.production.min.js:105
at _ (react-dom.production.min.js:125)
at D (react-dom.production.min.js:153)
at k (react-dom.production.min.js:143)
at P (react-dom.production.min.js:167)
at yn (react-dom.production.min.js:1622)
at ue (react-dom.production.min.js:7171)

Thanks for looking into it.

**Comment by Michael18811380328** [comment]
Hello cardinalfan1,
We tried chrome and safari on MacOS and follow these steps to reproduce the bug. After add these long string options, we search for "11011" and then click on the item. As shown below, it seems to work well. You can try the latest SeaTable (0.9.8) released on May 7th.

![May-11-2020 11-28-45](https://user-images.githubusercontent.com/37589122/81522153-21c4e100-937c-11ea-96c3-f68fdd81b5cd.gif)

**Comment by cardinalfan1** [comment]
Still not working for me. Tried updating to seatable 0.9.8. Does not seem to have to do with string length...

![screen](https://user-images.githubusercontent.com/22510021/81743179-e521e400-9466-11ea-8b42-b84b90794755.gif)

**Comment by freeplant** [comment]
Can you re-produce the problem in cloud.seatable.io? If so, you can then share the table with us.

**Comment by mpass3** [comment]
Hi @freeplant - please see: https://cloud.seatable.io/dtable/external-links/d5483b287a414119913c/
Try to select "Kanban" in the Purpose column.

**Comment by SolarDesalination** [comment]
I just tested again and oddly it works for some rows and not others; please try the "Kantree" row - Purpose field. 

Also, typing an option should **not** be case-sensitive. I don't think the use-case of case-sensitive for categories is more popular than the use-case of non-case sensitive for searching categories.

**Comment by freeplant** [comment]
The data of this row is somehow in a bad format. The problem will be fixed in the next release.
