### ISSUE TITLE
Could we get the row id inserted when we append / insert a row ?

### ISSUE THREAD

**Issue by mdartic** [seatable/seatable#47]
It could be useful to know it directly in the result of the append / insert request.

I'm actually searching a "good" way to make relations directly with the API.

Saying I have a table A, and table B, and a link between A & B.

When I insert a new row (or append) in A, it could be nice to know directly the row id generated.

I have to manually make a new request and find the new row id.

The same for the new row in B, I have to find the new row id.

After that, I could make another request to link the two rows.

Thanks for your help, and if you have an idea to make this process faster with the actual API, I'm listening to you :-)

**Comment by freeplant** [comment]
The fix will be included in version 1.0.0
