### ISSUE TITLE
Associate links with specific columns

### ISSUE THREAD

**Issue by sswatson** [seatable/seatable#48]
Based on the Python API and some experimentation with the interface, it appears that a _link_ is defined by four pieces of data: two table ids and two row ids. 

I would make the case for specifying _columns_ in the associated tables as well. The reason is that you often want to have two different columns in the same table which link to the same other table.

For example, consider a base with a "Food" table and a "People" table. A person record might contain a field for favorite foods and another field for foods they're allergic to. Currently it isn't possible to do that, because "favorites" and "allergies" will always have the same entries.

Here's an example: https://cloud.seatable.io/dtable/external-links/c017ac58964b4723af47/

**Comment by freeplant** [comment]
The fix will be included in the next release.

**Comment by freeplant** [comment]
The restful API and Python API for adding and removing is also updated.
