### ISSUE TITLE
Customisation of SeaTable : themes, logos, favicon

### ISSUE THREAD

**Issue by mdartic** [seatable/seatable#49]
Hello,

I've changed the favicon of our SeaTable instance, and the styles too.

When I upgraded to the 0.9.8, here are some things observed :
* logo / background / favicon didn't persist (maybe it's an error during my docker upgrade ?), but styles (css) were ok
* I changed again the favicon.ico, and when you refresh SeaTable web page, it's ok on the first load, but soon the favicon change again for the original one

I don't know if I can help, I didn't search a lot to understand why this happened.

**Comment by freeplant** [comment]
We will improve support for customization in a later version.

**Comment by mdartic** [comment]
Thank you
