### ISSUE TITLE
Geolocation selector in chinese only

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#51]
When we try to fill a Geolocation field, the selector is in chinese only.

![image](https://user-images.githubusercontent.com/4046624/82159030-e3538880-988b-11ea-9f7c-204318530af8.png)

**Comment by freeplant** [comment]
Do you add the option to enable Geolocation? By default, it is turned off.

**Comment by mont5piques** [comment]
No, I did not. The geolocation field type was available for selection without any action.
Note : I migrated from 0.9.7 to 0.9.8 if it could help.

**Comment by freeplant** [comment]
It will be fixed in version 1.0.0.
