### ISSUE TITLE
Feature: Lookup Column question

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#52]
Hi,

I wish to thank you again for the great product. I wait for Lookup Columns with impatience, I will be for me the most important feature for Seatable to have right now.

You said earlier that it will be available in 0.9.8. I guess it needs for developpement time and I understand. Do you think it will be available on 0.9.9 ?

> The feature you want is called "Lookup column" in other products. We will add such a feature in version 0.9.8.

You can close the issue afterwards.

Thanks a lot.

**Comment by freeplant** [comment]
The feature is finished now. It will be included in the next release in the beginning of June. The next release will be 1.0.0.

It is not a lookup column, but a function.

**Comment by mont5piques** [comment]
Cool. Very nice job.
