### ISSUE TITLE
Improvment: Date input should use field format

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#58]
When we create date fields with European Format, we still need to input it using ISO format.

**To Reproduce**
1. Go to any table
2. Add a new Column
3. Set Date as Type and European in Format
4. Create a new row and input a new date using keyboard (not the selector)

**Expected behavior**
The input should have the same format in the cell.

**Nota bene**  :
Most common european date format is not d/m/yyyy but dd/mm/yyyy.

http://www.europeword.com/blog/europe/european-date-format/

**Comment by freeplant** [comment]
Thanks for reporting the issue. We will check the problem.

**Comment by mont5piques** [comment]
Solved in 1.1.0
