### ISSUE TITLE
Convert Text Field to Multi-Select or Single Select field removes many entries

### ISSUE THREAD

**Issue by SolarDesalination** [seatable/seatable#59]
Hi,

Expected Result:
1. Import .csv file with column of many rows that has either "yes" or "no" as an answer
2. Select "Customize Column Type" select either "Multiple Select" or "Single Select"
3. "yes" and "no" answers will convert and categorize into options to be selected.

Current result:
3. Only one "yes", and one "no" response appear, all other rows become empty.

**Comment by freeplant** [comment]
The fix will be included in the next release 1.0.0.
