### ISSUE TITLE
docker restart on seatable container tries to re-init

### ISSUE THREAD

**Issue by jimzucker** [seatable/seatable#6]
Hi,

we started the container on a new install and it all works well but when we try a 'docker restart' on the beatable container it try's to initialize again and failed. 

Stoping removing and restarting it works OK.

**Comment by freeplant** [comment]
We will add logs to debug the problem in the next release. The next release will be available within 3 weeks.

**Comment by freeplant** [comment]
A new version 0.9.5 is ready! Please try again and give us feedbacks.

I suggest to delete old files and re-install the system.
