### ISSUE TITLE
CSV import specification

### ISSUE THREAD

**Issue by brejn** [seatable/seatable#60]
I was trying to import csv but whatever i try there's file error.
Is there any logging to see what exactly is the problem and is there documented how CSV should look.
For example what delimites are used etc.

**Comment by freeplant** [comment]
What version of SeaTable do you use?

**Comment by brejn** [comment]
0.9.8

**Comment by freeplant** [comment]
0.9.8 should not have this kind of issue. Can you try this CSV file on cloud.seatable.io ?

**Comment by brejn** [comment]
Ok i figured out the problem (user for the most part)
My regional settings are not standard US - comma for delimiter and dot for decimal separator.
It's semicolon for delimiter and comma for decimals.

Easy fix is to have option to define delimiter when importing CSV.

**Comment by freeplant** [comment]
Both ';' and ',' are now supported.
