### ISSUE TITLE
Improvment : Lock name field when scrolling horizontally

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#61]
Lock first colum/identifier column when scrolling horizontally as well as it's done with the row number.

**To Reproduce**
1. Pick up a table/view with a big number of columns
2. Scroll horizontally to the right
3. The row number is still visible (locked) and other fields are scrolled but not the "Name/first colum" that is used to identify the record (see image below).

**Expected behavior**
At step 3, we should have the first column locked also like the row number.

![image](https://user-images.githubusercontent.com/4046624/83008354-52ac4380-a015-11ea-87d4-9e4af9d9167b.png)

**Comment by freeplant** [comment]
There is already such a feature. Check the dropdown menu of the first column header.

**Comment by mont5piques** [comment]
Okay, the reason I didn't see it is that the option it is not shown until the scrollbar appears. This behavior could be confusing.
Thanks!
