### ISSUE TITLE
You can't have special characters in the views names otherwise the export in excel fails

### ISSUE THREAD

**Issue by bruhnild** [seatable/seatable#63]
For example, this view won't be exported apparently because of the `&` characters :

![image](https://user-images.githubusercontent.com/26433045/83233193-a42c0e00-a18e-11ea-93ce-6d2d07a638fc.png)

This case will work :

![image](https://user-images.githubusercontent.com/26433045/83233260-be65ec00-a18e-11ea-8a98-3a238ae54c78.png)

**Comment by freeplant** [comment]
The fix will be included in the next release.
