### ISSUE TITLE
The "number" columns are a problem during export to excel

### ISSUE THREAD

**Issue by bruhnild** [seatable/seatable#65]
I had several number type columns in my table and the export would not work.
The problem occured when I customized some text column to number columns, but for a strange reason it happened only to some number columns. For exemple, the first column (ID) is a number and I can still export the table to excel.

![image](https://user-images.githubusercontent.com/26433045/83035892-4b4b6100-a03a-11ea-851c-33ad51c61f08.png)

To make the export work, I had to :
- recreate the same fields in text format
- copy/paste the rows from the number columns to the text columns
- delete the number types columns

**Comment by freeplant** [comment]
Can you create a base with such a problem in cloud.seatable.io and share it to me?

**Comment by bruhnild** [comment]
Here is the link to access the table : https://cloud.seatable.io/dtable/links/91dd20c70c9846af9d6e

I create a view *debug* in the **Questionnaire** table with the problem column `commerceLocalTerrassePlace` so you can have a closer look.

I double checked and there are only number values in this field.

![bug](https://user-images.githubusercontent.com/26433045/83619594-606d4600-a58c-11ea-82d9-ba35f796de2b.gif)

**Comment by freeplant** [comment]
If I manually copy all the data to another table, the new table can be exported. So I guess there is a row with an invalid content that causing the problem.

I think you wrote the content via API. Some cell value may be invalid.

Can you export the base as a .dtable file and send to me? I will check the content in our development SeaTable instance.

**Comment by bruhnild** [comment]
Here is the .dtable file:

[dtable.zip](https://github.com/seatable/seatable/files/4750341/dtable.zip)

Thank you for the support!

**Comment by freeplant** [comment]
Thanks. The fix will be included in the next release.
