### ISSUE TITLE
Unable to access Table

### ISSUE THREAD

**Issue by ibqn** [seatable/seatable#68]
### I am struggling to view a Table directly after creating a base.
Once I have clicking on 'Add a base'  and creating a 'Test' table
![Screenshot from 2020-05-28 10-45-55](https://user-images.githubusercontent.com/234029/83120280-1b9b6800-a0d1-11ea-840c-5109d612b66e.png)

I am not able to access it at all.

![Screenshot from 2020-05-28 10-46-11](https://user-images.githubusercontent.com/234029/83120307-2950ed80-a0d1-11ea-92d6-ace43fa6adeb.png)

This is my docker-compose file
```docker-compose
version: '3.7'

services:
  db:
    image: mariadb:10.4
    container_name: seatable-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
    volumes:
      - seatable-db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seatable-net

  memcached:
    image: memcached:1.5.6
    container_name: seatable-memcached
    entrypoint: memcached -m 256
    networks:
      - seatable-net

  redis:
    image: redis:5.0.7
    container_name: seatable-redis
    networks:
      - seatable-net

  seatable:
    image: seafileltd/seatable:0.9.7
    container_name: seatable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./seatable:/shared # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=PASSWORD  # Requested, the value shuold be root's password of MySQL service.
      - SEATABLE_SERVER_LETSENCRYPT=False # Default is False. Whether to use let's encrypt certificate.
      - SEATABLE_SERVER_HOSTNAME=tom.seatable.local # Specifies your host name.
      - TIME_ZONE=Etc/UTC # Optional, default is UTC. Should be uncomment and set to your local time zone.
    depends_on:
      - db
      - memcached
      - redis
    networks:
      - seatable-net

networks:
  seatable-net:

volumes:
  seatable-db: {}

```

additionally I have created an entry in `etc/hosts` with

```shell
127.0.0.1        tom.seatable.local
```

Do I miss something? Any suggestion are highly appreciated.

**Comment by freeplant** [comment]
Please check this thread: https://github.com/seatable/seatable/issues/9

**Comment by ibqn** [comment]
in `error.log` I also see this line

```shell
2020/05/28 09:07:33 [error] 32#32: *55 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: tom.seatable.local, request: "GET /dtable-server/dtables/82a73fd601c44f27bf7b98cf5623d8bc?lang=en HTTP/1.1", upstream: "http://127.0.0.1:5000/dtables/82a73fd601c44f27bf7b98cf5623d8bc?lang=en", host: "tom.seatable.local", referrer: "http://tom.seatable.local/workspace/1/dtable/Test/"
```

**Comment by ibqn** [comment]
@freeplant thanks for the hint

I do not see anything strange in those configurations

dtable_server_config.json
```

{
    "host": "db",
    "user": "root",
    "password": "PASSWORD",
    "database": "dtable_db",
    "port": 3306,
    "private_key": "s+f_&xe&g$5=4@_+hd8(gja6k%in8l1_gfmcv(^!)8wjyh)=o2",
    "dtable_web_service_url": "http://tom.seatable.local/",
    "redis_host": "redis",
    "redis_port": 6379,
    "redis_password": ""
}

```

and dtable_web_settings.py

```python

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'db',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'PASSWORD',
        'NAME': 'dtable_db',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_pylibmc.memcached.PyLibMCCache',
        'LOCATION': 'memcached',
    },
    'locmem': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}
COMPRESS_CACHE_BACKEND = 'locmem'

# for dtable-server
DTABLE_PRIVATE_KEY = 's+f_&xe&g$5=4@_+hd8(gja6k%in8l1_gfmcv(^!)8wjyh)=o2'
DTABLE_SERVER_URL = 'http://tom.seatable.local/dtable-server/'
DTABLE_SOCKET_URL = 'http://tom.seatable.local/'

# for dtable-web
DTABLE_WEB_SERVICE_URL = 'http://tom.seatable.local/'

# for seaf-server
FILE_SERVER_ROOT = 'http://tom.seatable.local/seafhttp/'

```
Please correct me if I am wrong :-)

**Comment by freeplant** [comment]
What error message do you have in dtable-server.log?

**Comment by ibqn** [comment]
@freeplant the `dtable-server.log` is completely empty, I guess the issue is somewhere in the nginx configuration. It seems that request are never getting routed to the dtable-server for some reason.

**Comment by freeplant** [comment]
If dtable-server.log is empty, it is likely dtable-server is not started. You can login into the docker container and check the process.

**Comment by ibqn** [comment]
@freeplant for some reason it is not stated by the `seatable.sh` script.

If I start it manually with (after sourcing the env variables)

```shell
node dist/src/index.js &>>/opt/seatable/logs/dtable-server.log &
```

, then I get the following errors in the `dtable-server.log`

```shell
[2020-05-28T12:55:28.268] [INFO] dtable-server - Starting dtable server process: 223
[2020-05-28T12:55:28.282] [INFO] dtable-server - listening on port 5000
[2020-05-28T12:55:36.167] [ERROR] dtable-server - Dtable load failed
[2020-05-28T12:55:38.642] [ERROR] dtable-server - Dtable load failed
[2020-05-28T12:55:44.176] [ERROR] dtable-server - Dtable load failed

```

**Comment by freeplant** [comment]
Can you access http://tom.seatable.local within the docker container?

**Comment by asp100m** [comment]
@ibqn the issue is closed, so I reply here.

You can check the host is accessible or not by following steps.
1. Get into the container
`$ sudo docker exec -it seatable /bin/bash`

2. Check full name
`# curl -L http://tom.seatable.local/`

3. Check short name
`# curl -L http://tom/`

If you get some html code, it means they are different problems.
The expected output is `curl: (6) Could not resolve host: tom.seatable.local`

**Comment by ibqn** [comment]
@freeplant, @asp100m Thank you guys for the help.

I have managed to get it working with (by you @asp100m in the another thread ) discovered workaround.

Steps to get there: 

I went into this container with `docker-compose exec seatable bash`, then installed `ping` command with `apt install iputils-ping` 

and of cause as expected `tom.seatable.local` is not known within the container.

```shell
root@04904f370e20:/opt/seatable# ping tom.seatable.local
ping: tom.seatable.local: Name or service not known
```

as a workaround to get seatable working in the docker container I have added this line `127.0.0.1        tom.seatable.local` to `etc/hosts` in this container.

Therefore, to summarize there is a clear bug to me in this setup.

The `dtable-server` service should not rely at all on the container host name resolution, this should be avoided by a better `nginx` configuration. 

Another issue is that the `dtable-server` failed to start silently  by running this script (due to the above issue, I assume)

```shell
bash docker-compose.bash exec -d seatable /shared/seatable/scripts/seatable.sh start
```

There a definitely improvements needed from my point of view.

Thanks, one more time.

**Comment by freeplant** [comment]
> The dtable-server service should not rely at all on the container host name resolution, this should be avoided by a better nginx configuration.

The different  components inside the container need to talk to each other via the URL. Nginx along can't solve the problem.
