### ISSUE TITLE
The switch formula seems to be not working with injected rows

### ISSUE THREAD

**Issue by bruhnild** [seatable/seatable#70]
The switch formula of the following columns commerceNoteBati, commerceNoteDevanture et commerceNoteVitrine are not executed when a row is injected in the table.
But when I try to edit the columns commerceNoteBati_1, commerceNoteDevanture_1 et commerceNoteVitrine_1 the formula are working.

![formula](https://user-images.githubusercontent.com/26433045/83238804-40f2a980-a197-11ea-955f-5395a206eb6a.gif)

**Comment by freeplant** [comment]
This is because a function column is not supported in formula yet.

**Comment by bruhnild** [comment]
Yes, but the columns commerceNoteBati_1, commerceNoteDevanture_1 and commerceNoteVitrine_1 are not function columns, there are text columns and there are used by commerceNoteBati, commerceNoteDevanture and commerceNoteVitrine

Here is one of the formula I use : 
`switch({commerceNoteVitrine_1}, "0", "Mauvaise", "1", "Passable","2", "Moyen","3", "Bien","4", "Très bien","5", "Excellent","" ) `

**Comment by freeplant** [comment]
What do you mean by **injected rows**?

Maybe it is a rendering problem. Refreshing the page will show the function results.

**Comment by bruhnild** [comment]
I checked and it's not a rendering problem.

We use the Seatable API to inject data from a form online.

**Comment by freeplant** [comment]
Can you create a base in cloud.seatable.io, reproduce the problem and share the base to me?

**Comment by bruhnild** [comment]
Hi, I think I found something else connected with my issue 

![Peek 04-08-2020 16-40](https://user-images.githubusercontent.com/26433045/89309397-aa99a300-d673-11ea-85ef-356de1154fa4.gif)

I created a formula to concatenate several columns to gather an address

`if(len({adresse_1})>0,{adresse_1}, concatenate({numeroVoieEtablissement},  " " ,  {indiceRepetitionEtablissement},  " ",  {typeVoieEtablissement}," ", {libelleVoieEtablissement},  " ", {codePostalEtablissement}, " " , {LibelleCommuneEtablissement})) 
`
I realized that there is no space between words of columns used in the formula, for exemple  :`11RUEDESGENERAUXALTMAYER`  instead of `11 RUE DES GENERAUX ALTMAYER` .

When I stard editing a cell in a column used in the formula, the formula update the value of the row.
