### ISSUE TITLE
The columns of Default View are not all exported in Excel

### ISSUE THREAD

**Issue by bruhnild** [seatable/seatable#71]
When I export the Default view in excel, there are missing columns .
For example, in my table the last columns are not exported in the excel file.

rue_vacancecontact | _idTripetto | Crée le | Modifié le | Modificateur

![export](https://user-images.githubusercontent.com/26433045/83248914-13f9c300-a1a6-11ea-94a2-7e37ed17910c.gif)

**Comment by freeplant** [comment]
It should have been fixed in the latest 1.2 version.
