### ISSUE TITLE
docker image not working, python issue?

### ISSUE THREAD

**Issue by acao** [seatable/seatable#73]
these docs don't seem to be working:

https://docs.seatable.io/published/seatable-manual/docker/ce-edition/Deploy%20SeaTable-ce%20with%20Docker.md

these commands specifically:

`docker exec -it seatable /shared/seatable/scripts/seatable.sh start`

throw errors like:

```
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%d{>c'
```

(this error is from `image: seafileltd/seatable:0.9.3`). i have tried every 0.9.x version, and each gives me a different python error on running the seatable.sh commands

i noticed that the seatable arch container is running python 3 by default

**Update**

with latest 1.0.0 tag i just saw this morning:

`start` works on the first run, but then if i run `stop` command, and `start` again, i get 

```js
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 25 (char 65)
```

also `superadmin` fails the same way

**Comment by freeplant** [comment]
It is likely cased by an error in your config file, dtable_server_config.json, as it is in json format.

You can try to remove all the installation folder and start from clean again.

**Comment by acao** [comment]
tried this with the 1.0.0 update, deleting `seatable-data` and ran it again. seemed to fix the nginx conf issue, now has an entry for 443. possibly there's a manual configuration step missing from the docs above?

**Comment by acao** [comment]
ah! it was some of the password characters. thank you

**Comment by acao** [comment]
so, start/stop seem to work fine now, but still a json parsing issue with superadmin command, looking into other JSON config files
