### ISSUE TITLE
User database error

### ISSUE THREAD

**Issue by pyrot23** [seatable/seatable#76]
I updated seatable image from 0.9.8 to version 1.0.0. When go to setting->user site, both database and admins tab shows error (no user is listed, only shows the text error in red text). I can still export the user list to Excel though. 

![2020-06-03_userError](https://user-images.githubusercontent.com/31209618/83597370-b399c580-a599-11ea-8049-da10cbbe0e67.png)

**Comment by freeplant** [comment]
Have you upgraded MySQL database?

**Comment by pyrot23** [comment]
no, the mariadb that I use remains untouched

**Comment by freeplant** [comment]
I mean have you run the database upgrade script according to the upgrade document: https://docs.seatable.io/published/seatable-manual/upgrade/upgrade_manual.md

**Comment by pyrot23** [comment]
apparently I didn't see the upgrade manual. thank you very much.
