### ISSUE TITLE
share table action doesn't show user list

### ISSUE THREAD

**Issue by pyrot23** [seatable/seatable#77]
when share a table to user, the drop down menu doesn't show any name. member name only appears only when I type the name into search box. 

![2020-06-03_shareError](https://user-images.githubusercontent.com/31209618/83597261-75040b00-a599-11ea-8322-1ef9d7bc8197.png)

I have compared the functionality with share to group, all the suitable groups appears in the drop down list.

**Comment by freeplant** [comment]
The UI will be improved in the next release.
