### ISSUE TITLE
Mixed content - dtable is not shown

### ISSUE THREAD

**Issue by aiveras** [seatable/seatable#8]
When using seatable behind a reverse proxy the spreadsheet connection is not secure..
How can we prevent this?

**Comment by freeplant** [comment]
Make sure your URL settings are right. Please check https://docs.seatable.io/published/seatable-manual/config/dtable_web_settings.md . Especially DTABLE_SERVER_URL and DTABLE_SOCKET_URL

**Comment by aiveras** [comment]
I set both in the docker-compose.yml but in the container it's still http and not https

**Comment by freeplant** [comment]
The URLs in docker-compose.yml only take effect for the first time when generating the config files. Later you need to modify the config files directly.
