### ISSUE TITLE
Blank page for dtable on HTTPS

### ISSUE THREAD

**Issue by gauburti** [seatable/seatable#81]
Hi,

We never managed to make i work on HTTPS.
We update on 1.0.0 and it does not work neither

Installing version 1.0.0:

docker pull seafileltd/seatable:1.0.0

      mkdir /opt/seatable && cd $_

      wget
https://docs.seatable.io/seafhttp/files/52f00c70-1263-4f30-97dc-5fdfbabc4e12/docker-compose.yml

      editing docker-compose.yaml file (see attachment)
docker-compose up
retrieving nginx conf file from previous installation, since 1.0.0 installation didn't build the file (see attachment)

[nginx.conf.txt](https://github.com/seatable/seatable/files/4736347/nginx.conf.txt)
[docker-compose.yaml.txt](https://github.com/seatable/seatable/files/4736348/docker-compose.yaml.txt)

docker-compose up -d

      docker exec -d seatable
        /shared/seatable/scripts/seatable.sh start

      docker exec -it seatable
        /shared/seatable/scripts/seatable.sh superuser 

Testing:

seatable can be reached at its URL seatable-test.domain.fr, https rewrite is OK, such as account creation, etc.

But database viewing / editing does not work:

For instance, after creating an empty database named TEST, trying to access https://seatable-test.domain.fr/workspace/1/dtable/TEST/ gives the following errors:
request URL : https://seatable-test.domain.fr/media/locales/fr/dtable.json?v=1.0.0 => 404 error
Nota: this problem is solved when setting the interface language in English

request URL : https://seatable-test.domain.fr/dtable-server/dtables/8f66539de5b349a688450c034a961f59?lang=fr => 500 error
Same thing in English:
request URL : https://seatable-test.domain.fr/dtable-server/dtables/8f66539de5b349a688450c034a961f59?lang=en => 500 error

The logs show that not a single */dtable-server/ URL has been served OK, so the problem likely lies in the nginx configuration for this location, or within the process whiurlsch is behind this location.

All conf files inside seatable have HTTPS urls

Investigations:

For the /dtable-server location, nginx configuration is the following:
    location /dtable-server {

                            # add_header Access-Control-Allow-Origin *;

                            if ($request_method = 'OPTIONS') {

                                add_header Access-Control-Allow-Origin
                    *;

                                add_header Access-Control-Allow-Methods
                    GET,POST,PUT,DELETE,OPTIONS;

                                add_header Access-Control-Allow-Headers
                    "deviceType,token, authorization, content-type";

                                return 204;

                            }

                            #rewrite /dtable-server/(.*) /$1 break;

                        rewrite ^/dtable-server/(.*)$ /$1 break;

                            proxy_pass         http://dtable_servers;

                        #try

                        #proxy_headers_hash_max_size 512;

                        #proxy_headers_hash_bucket_size 64;

                            proxy_redirect     off;

                            proxy_set_header   Host              $host;

                            proxy_set_header   X-Real-IP        
                    $remote_addr;

                            proxy_set_header   X-Forwarded-For  
                    $proxy_add_x_forwarded_for;

                            proxy_set_header   X-Forwarded-Host 
                    $server_name;

                            proxy_set_header   X-Forwarded-Proto
                    $scheme;

                        }

                  

Hosts group dtable_servers (referred to in the proxy_pass directive) is defined at the top of the nginx configuration file:
upstream dtable_servers {

                      server 127.0.0.1:5000;     

                      keepalive 15;

                  }

Looking for the process which is using the #5000 port (edc8410e172b is the container ID of the seatable container):
root@edc8410e172b:/etc/nginx/sites-enabled#
                    ss -ltp | grep 5000

                    LISTEN   0         128                      
                    *:5000                   *:*        users"node",pid=91,fd=19))
                    

                  

                  
root@edc8410e172b:/etc/nginx/sites-enabled#
                    ps -p 91 -f

                  UID        PID  PPID  C STIME TTY         
                    TIME CMD

                  root        91     1  0 Jun04 ?       
                    00:00:01 node dist/src/index.js

I did not investigate further, as node is far beyond my knowledges.

Additional informations:
we replaced the Let's Encrypt certificate with our own, this does not seem to cause any problem to

**Comment by gauburtincc** [comment]
First error detected on Firefox debugger

Sheet.js

SyntaxError: An invalid or illegal string was specified

```
_insert: function _insert(rule) {
    // this weirdness for perf, and chrome's weird bug 
    // https://stackoverflow.com/questions/20007992/chrome-suddenly-stopped-accepting-insertrule
    try {
      var sheet = this.getSheet();
      sheet.insertRule(rule, rule.indexOf('@import') !== -1 ? 0 : sheet.cssRules.length);
```

Then 

media/assets/frontend/static/node_modules/react-select/dist/react-select.esm.js

NotSupportedError: Operation is not supported
```

} // Touch Capability Detector
// ==============================


function isTouchCapable() {
  try {
    document.createEvent('TouchEvent');
```

Then 

media/assets/frontend/static/node_modules/axios/lib/defaults.js

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

```
 transformResponse: [function transformResponse(data) {
    /*eslint no-param-reassign:0*/
    if (typeof data === 'string') {
      try {
        data = JSON.parse(data);
      } catch (e) {
        /* Ignore */
      }
    }
```

**Comment by freeplant** [comment]
The Nginx config is not re-generated because there is an old file.

What's your dtable_web_service_url setting in dtable_server_config.json? Make sure it start with https if you want to switch to https.

**Comment by gauburtincc** [comment]
As i mentionned above all the config files starts with HTTPS, including dtable_server_config.json.

I thought that we culd have the same issue as https://github.com/seatable/seatable/issues/68

DNS resolution is OK for the IP of the VM that hosts the container

But on HTTPS we get a SSL issue (quite logic if the container does not have access to the certs)

curl -L  https://seatable-test.domain.fr
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

**Comment by Vinc89** [comment]
I had the same issue as described. Managed to get HTTPS working.

1) Make you have a chain certificate included in your certificate file.
 `"cat chain certificate >> server certificate"`
Nginx does not have a chain certificate directive so both certificates need to be in 1 file.

I had the same error as gauburtincc without the chain certificate
`curl https://seatable.url
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html`

2) If you are using proxy in front of the container configure the HTTPS proxy.
my apache example
`       SSLProxyEngine on

        SSLProxyCheckPeerCN on
        SSLProxyCheckPeerExpire on
        ProxyPreserveHost On
        ProxyPass /    https://127.0.0.1:port/
        ProxyPassReverse / https://127.0.0.1:port/`

3) nginx.conf contains only the https server
```
server {

    listen 443 ssl;
    server_name seatable.hostname;

    ssl_certificate /shared/ssl/domain.crt;
    ssl_certificate_key /shared/ssl/domain.key;
    proxy_set_header X-Forwarded-For $remote_addr;
    .....
```

4) the /etc/hosts file needs to have the entry
127.0.0.1 $SEATABLE_SERVER_HOSTNAME

**Comment by ArjonBu** [comment]
I made an issue here: https://github.com/seatable/seatable/issues/122 

Basically I think nginx should be removed completely from the container. This way it's much easier to manage the reverse proxy without having to go dirty inside the container. It's always better to have a container per service and it's not good practice to include the reverse proxy inside the app container.

**Comment by Starkmann** [comment]
I had the same issue. I wanted a apache proxy with ssl before seatables and no ssl insite of the container.

I ended up changing the urls in dtable_web_settings.py from http to https.

And now everything is working.
