### ISSUE TITLE
Use existing mariadb instance

### ISSUE THREAD

**Issue by Leosirth** [seatable/seatable#84]
Hi,

I would like to use an existing mariadb container instead to spawn a new one only for seatable.
Can this be achieved?
In case it's not possible right now, do you plan to add this in future release?

Thanks and regards,

**Comment by freeplant** [comment]
If you want to use existing mariadb, you can first finish installation, then migrate the data from the default mariadb to your existing mariadb, modify the config files and docker-compose.yml.
