### ISSUE TITLE
Blank web page after creating new table.

### ISSUE THREAD

**Issue by Janilom** [seatable/seatable#9]
I just configured Seatable. I am able to access the site as well as create tables . However, after clicking on the table its just a blank white web page.

**Comment by freeplant** [comment]
Make sure the URL for DTABLE_SERVER_URL, DTABLE_SOCKET_URL, DTABLE_WEB_SERVICE_URL in dtable_web_setting.py and dtable_web_service_url in 
dtable_server_config.json is correct. 

Our documents:

https://docs.seatable.io/published/seatable-manual/config/dtable_server_config.md

https://docs.seatable.io/published/seatable-manual/config/dtable_web_settings.md

**Comment by asp100m** [comment]
I got into this problem too and found the cause. It probably is the service in container can't resolve the hostname of itself.
To figure it out, you can add a record to /etc/hosts in the container of seatable.

**Comment by ibqn** [comment]
@asp100m Was you able to resole this issue?

I have added an entry in the `/etc/hosts` without and success.

![Screenshot from 2020-05-28 11-50-21](https://user-images.githubusercontent.com/234029/83126967-d9c2ef80-a0d9-11ea-9ae3-36f0bcda8021.png)


Can you please elaborate your suggestion by providing an example.

And If I understand you correctly, you say that this setup is generally broken, right?

**Comment by ibqn** [comment]
@freeplant any ideas?

**Comment by iamsunxing** [comment]
The same question. How to solve ?
