### ISSUE TITLE
[BUG] Directional keys don't work after new cell creation

### ISSUE THREAD

**Issue by mont5piques** [seatable/seatable#94]
When we create create a new cell in a new row, we can't use arrows key anymore.

**To Reproduce**

- Go to any table
- Add a new row
- Select the Name column for example and start typing
- Type "Enter" to save the input
- Use left / right keys or up / down keys to move accross the cells. **It doesn't work.**
- Click again on the cell
- Use left / right keys or up / down keys to move accross the cells. **It does work.**

**Expected behavior**
The directional keys should be usable after hitting "Enter".

**Comment by freeplant** [comment]
The fix will be included in version 1.1.
