### ISSUE TITLE
Trying to understand DB structure

### ISSUE THREAD

**Issue by doodlemania2** [seatable/seatable#95]
I'm trying to understand the DB structure so I can grab updates and write my own websocket API but cannot seem to find where the data for my tables are stored, except possibly via a construction in Activities. The reason for the ask is the API for websockets doesn't return value names for Single and Multi selects, but rather, a key. A doc on the structure of the db would be most helpful.

**Comment by freeplant** [comment]
You can print metadata of a base via the API: https://docs.seatable.io/published/seatable-api/python/seatable-api.md#user-content-Get%20Seatable%20Metadata

From the metadata, you can get the option name for a select key.

We will add API to convert select option soon.
