### ISSUE TITLE
Cross-Origin Request Blocked:

### ISSUE THREAD

**Issue by gerroon** [seatable/seatable#98]
Hi

I am using this internally so I put the hostname of my server in the Docker compose file 

SEATABLE_SERVER_HOSTNAME=DOMAIN

However my browser is blocking the connection so I cant access the tables.

`
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://DOMAIN/dtable-server/dtables/449a82e655e0489a825d333adc7113a0?lang=en. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
`

**Comment by freeplant** [comment]
Maybe you are mixing http with https

**Comment by gerroon** [comment]
I am not mixing it at all, I am using it inside the LAN so no htttps is involved and SSL is disabled.  

The address for it is `http://DOMAIN:3131`

**Comment by shoeper** [comment]
Looks like you access it at http://DOMAIN:3131 and it tries to load http://DOMAIN:80 which is a cross origin access you have to allow using a CORS policy.

**Comment by gerroon** [comment]
@shoeper 

Thanks for the reply. I am not literate in this stuff. How do I do that?

thanks
